// <auto-generated />
namespace Fogvent.Data.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SecurityEntitiesChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecurityEntitiesChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201710010921092_SecurityEntitiesChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
